"""make display_name nullable on user and therapist

Revision ID: 21c691d3f693
Revises: 58d6be0cd3de
Create Date: 2026-02-11 00:21:28.480261

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '21c691d3f693'
down_revision = '58d6be0cd3de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('therapist', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('therapist', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
