"""add access request table

Revision ID: 58d6be0cd3de
Revises: 533a19db5a8b
Create Date: 2026-02-09 20:53:35.650548

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '58d6be0cd3de'
down_revision = '533a19db5a8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neon_auth_sub', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_request_email'), 'access_request', ['email'], unique=False)
    op.create_index(op.f('ix_access_request_neon_auth_sub'), 'access_request', ['neon_auth_sub'], unique=True)
    op.create_index(op.f('ix_access_request_status'), 'access_request', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_request_status'), table_name='access_request')
    op.drop_index(op.f('ix_access_request_neon_auth_sub'), table_name='access_request')
    op.drop_index(op.f('ix_access_request_email'), table_name='access_request')
    op.drop_table('access_request')
    # ### end Alembic commands ###
