"""schema sync

Revision ID: 7a1880953eac
Revises: 0001_initial
Create Date: 2026-02-05 23:13:16.281723

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '7a1880953eac'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
