"""add physio_id to session_note

Revision ID: 9ce8dd928472
Revises: 7a1880953eac
Create Date: 2026-02-06 15:44:45.450218

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '9ce8dd928472'
down_revision = '7a1880953eac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessionnote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sessionnote_physio_id_user', 'user', ['physio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessionnote', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessionnote_physio_id_user', type_='foreignkey')
        batch_op.drop_column('physio_id')
    # ### end Alembic commands ###
