"""v1_initial_schema

Revision ID: ab5432edcf4e
Revises: 
Create Date: 2026-02-07 00:08:56.982030

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



revision = 'ab5432edcf4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapistspecialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapistspecialty_name'), 'therapistspecialty', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neon_auth_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_neon_auth_sub'), 'user', ['neon_auth_sub'], unique=True)
    op.create_table('therapist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('calendly_user_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapist_user_id'), 'therapist', ['user_id'], unique=True)
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_therapist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['preferred_therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_phone_e164'), 'client', ['phone_e164'], unique=True)
    op.create_table('therapist_event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('calendly_event_type_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduling_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapist_event_type_calendly_event_type_uri'), 'therapist_event_type', ['calendly_event_type_uri'], unique=True)
    op.create_index(op.f('ix_therapist_event_type_therapist_id'), 'therapist_event_type', ['therapist_id'], unique=False)
    op.create_table('therapist_specialty_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['therapistspecialty.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('therapist_id', 'specialty_id')
    )
    op.create_index(op.f('ix_therapist_specialty_map_specialty_id'), 'therapist_specialty_map', ['specialty_id'], unique=False)
    op.create_index(op.f('ix_therapist_specialty_map_therapist_id'), 'therapist_specialty_map', ['therapist_id'], unique=False)
    op.create_table('client_financial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('total_paid_cents', sa.Integer(), nullable=False),
    sa.Column('total_receipted_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_financial_client_id'), 'client_financial', ['client_id'], unique=True)
    op.create_table('matching_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('requested_duration', sa.Integer(), nullable=True),
    sa.Column('requested_specialty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_time_band', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_days', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('selected_therapist_id', sa.Integer(), nullable=True),
    sa.Column('scoring_breakdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('fallback_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['selected_therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_decision_client_id'), 'matching_decision', ['client_id'], unique=False)
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twilio_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_log_client_id'), 'message_log', ['client_id'], unique=False)
    op.create_index(op.f('ix_message_log_phone_e164'), 'message_log', ['phone_e164'], unique=False)
    op.create_index(op.f('ix_message_log_twilio_sid'), 'message_log', ['twilio_sid'], unique=True)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('charge_amount_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calendly_event_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('calendly_invitee_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('therapist_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_calendly_event_uri'), 'session', ['calendly_event_uri'], unique=True)
    op.create_index(op.f('ix_session_client_id'), 'session', ['client_id'], unique=False)
    op.create_index(op.f('ix_session_therapist_id'), 'session', ['therapist_id'], unique=False)
    op.create_table('payment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_record_recorded_by_user_id'), 'payment_record', ['recorded_by_user_id'], unique=False)
    op.create_index(op.f('ix_payment_record_session_id'), 'payment_record', ['session_id'], unique=False)
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issued_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_client_id'), 'receipt', ['client_id'], unique=False)
    op.create_index(op.f('ix_receipt_issued_by_user_id'), 'receipt', ['issued_by_user_id'], unique=False)
    op.create_table('session_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_note_author_user_id'), 'session_note', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_session_note_session_id'), 'session_note', ['session_id'], unique=False)
    op.create_table('payment_proof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_record_id', sa.Integer(), nullable=False),
    sa.Column('proof_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_record_id'], ['payment_record.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_proof_payment_record_id'), 'payment_proof', ['payment_record_id'], unique=False)
    op.create_index(op.f('ix_payment_proof_uploaded_by_user_id'), 'payment_proof', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_proof_uploaded_by_user_id'), table_name='payment_proof')
    op.drop_index(op.f('ix_payment_proof_payment_record_id'), table_name='payment_proof')
    op.drop_table('payment_proof')
    op.drop_index(op.f('ix_session_note_session_id'), table_name='session_note')
    op.drop_index(op.f('ix_session_note_author_user_id'), table_name='session_note')
    op.drop_table('session_note')
    op.drop_index(op.f('ix_receipt_issued_by_user_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_client_id'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_payment_record_session_id'), table_name='payment_record')
    op.drop_index(op.f('ix_payment_record_recorded_by_user_id'), table_name='payment_record')
    op.drop_table('payment_record')
    op.drop_index(op.f('ix_session_therapist_id'), table_name='session')
    op.drop_index(op.f('ix_session_client_id'), table_name='session')
    op.drop_index(op.f('ix_session_calendly_event_uri'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_message_log_twilio_sid'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_phone_e164'), table_name='message_log')
    op.drop_index(op.f('ix_message_log_client_id'), table_name='message_log')
    op.drop_table('message_log')
    op.drop_index(op.f('ix_matching_decision_client_id'), table_name='matching_decision')
    op.drop_table('matching_decision')
    op.drop_index(op.f('ix_client_financial_client_id'), table_name='client_financial')
    op.drop_table('client_financial')
    op.drop_index(op.f('ix_therapist_specialty_map_therapist_id'), table_name='therapist_specialty_map')
    op.drop_index(op.f('ix_therapist_specialty_map_specialty_id'), table_name='therapist_specialty_map')
    op.drop_table('therapist_specialty_map')
    op.drop_index(op.f('ix_therapist_event_type_therapist_id'), table_name='therapist_event_type')
    op.drop_index(op.f('ix_therapist_event_type_calendly_event_type_uri'), table_name='therapist_event_type')
    op.drop_table('therapist_event_type')
    op.drop_index(op.f('ix_client_phone_e164'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_therapist_user_id'), table_name='therapist')
    op.drop_table('therapist')
    op.drop_index(op.f('ix_user_neon_auth_sub'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_therapistspecialty_name'), table_name='therapistspecialty')
    op.drop_table('therapistspecialty')
    # ### end Alembic commands ###
