"""add_billing_expansions

Revision ID: df03baf0ef2f
Revises: 8d9f4af7c2b6
Create Date: 2026-02-23 14:17:17.598910

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

revision = 'df03baf0ef2f'
down_revision = '8d9f4af7c2b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_preset_is_active'), 'invoice_preset', ['is_active'], unique=False)
    op.create_index(op.f('ix_invoice_preset_preset_type'), 'invoice_preset', ['preset_type'], unique=False)
    op.create_index(op.f('ix_invoice_preset_sort_order'), 'invoice_preset', ['sort_order'], unique=False)
    op.create_index(op.f('ix_invoice_preset_updated_at'), 'invoice_preset', ['updated_at'], unique=False)
    op.alter_column('billing_plan', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('billing_plan', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('client', sa.Column('default_receipt_amount_cents', sa.Integer(), nullable=True))
    op.alter_column('client_plan_assignment', 'effective_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('client_plan_assignment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('client_plan_assignment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('payment_record', sa.Column('client_id', sa.Integer(), nullable=True))
    op.execute('''
        UPDATE payment_record 
        SET client_id = session.client_id 
        FROM session 
        WHERE payment_record.session_id = session.id
    ''')
    op.alter_column('payment_record', 'client_id', nullable=False)

    op.add_column('payment_record', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True))
    op.execute("UPDATE payment_record SET source = 'session_linked'")
    op.alter_column('payment_record', 'source', nullable=False)
    op.alter_column('payment_record', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payment_record', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_payment_record_client_id'), 'payment_record', ['client_id'], unique=False)
    op.create_foreign_key(None, 'payment_record', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_record', type_='foreignkey')
    op.drop_index(op.f('ix_payment_record_client_id'), table_name='payment_record')
    op.alter_column('payment_record', 'paid_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('payment_record', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payment_record', 'source')
    op.drop_column('payment_record', 'client_id')
    op.alter_column('client_plan_assignment', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('client_plan_assignment', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('client_plan_assignment', 'effective_from',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('client', 'default_receipt_amount_cents')
    op.alter_column('billing_plan', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('billing_plan', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoice_preset_updated_at'), table_name='invoice_preset')
    op.drop_index(op.f('ix_invoice_preset_sort_order'), table_name='invoice_preset')
    op.drop_index(op.f('ix_invoice_preset_preset_type'), table_name='invoice_preset')
    op.drop_index(op.f('ix_invoice_preset_is_active'), table_name='invoice_preset')
    op.drop_table('invoice_preset')
    # ### end Alembic commands ###
